/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0 Component Pack 7
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Em_EEPROM_1.h>
#include <LCD_Char_1.h>
#include <Pin_1.h>
#include <Pin_1_aliases.h>
#include <ADC_DelSig_2.h>
#include <isr_1.h>
#include <Pin_2.h>
#include <Pin_2_aliases.h>
#include <LCD_Char_1_LCDPort.h>
#include <LCD_Char_1_LCDPort_aliases.h>
#include <ADC_DelSig_2_AMux.h>
#include <ADC_DelSig_2_Ext_CP_Clk.h>
#include <ADC_DelSig_2_IRQ.h>
#include <ADC_DelSig_2_theACLK.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/

