# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Win7_VM\Documents\PSoC Creator\Erebus_Sensor\Erebus_Sensor.cydsn\Erebus_Sensor.cyprj
# Date: Wed, 02 Apr 2014 03:45:13 GMT
#set_units -time ns
create_clock -name {ADC_Ext_CP_Clk(routed)} -period 15.625 -waveform {0 7.8125} [list [get_pins {ClockBlock/dclk_0}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyPLL_OUT} -period 15.625 -waveform {0 7.8125} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyILO} -period 10000 -waveform {0 5000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyMASTER_CLK} -period 15.625 -waveform {0 7.8125} [list [get_pins {ClockBlock/clk_sync}]]
create_clock -name {ADC_Ext_CP_Clk} -period 15.625 -waveform {0 7.8125} [list [get_pins {ClockBlock/dclk_glb_0}]]
create_generated_clock -name {debounce_clock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 640001 1280001} [list [get_pins {ClockBlock/dclk_glb_1}]]
create_generated_clock -name {timer_clock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 64001 128001} [list [get_pins {ClockBlock/dclk_glb_2}]]
create_clock -name {timer_clock(fixed-function)} -period 1000000 -waveform {0 15.625} [get_pins {ClockBlock/dclk_glb_ff_2}]
create_generated_clock -name {ADC_theACLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 427 855} [list [get_pins {ClockBlock/aclk_glb_0}]]
create_clock -name {ADC_theACLK(fixed-function)} -period 6671.875 -waveform {0 3335.9375} [get_pins {ClockBlock/aclk_glb_ff_0}]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]

set_false_path -from [get_pins {__ONE__/q}]

# Component constraints for C:\Users\Win7_VM\Documents\PSoC Creator\Erebus_Sensor\Erebus_Sensor.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Win7_VM\Documents\PSoC Creator\Erebus_Sensor\Erebus_Sensor.cydsn\Erebus_Sensor.cyprj
# Date: Wed, 02 Apr 2014 03:45:07 GMT
