/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0 Component Pack 7
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <USBUART.h>
#include <USBUART_audio.h>
#include <USBUART_cdc.h>
#include <USBUART_hid.h>
#include <USBUART_midi.h>
#include <USBUART_pvt.h>
#include <Blink_Timer.h>
#include <LED.h>
#include <LED_aliases.h>
#include <timer_clock.h>
#include <Vbus.h>
#include <Vbus_aliases.h>
#include <VbusHigh_IRQ.h>
#include <EEPROM_R.h>
#include <debounce_clock.h>
#include <VbusLow_IRQ.h>
#include <USB_LED.h>
#include <USB_LED_aliases.h>
#include <EEPROM_LED.h>
#include <EEPROM_LED_aliases.h>
#include <USBUART_Dm.h>
#include <USBUART_Dm_aliases.h>
#include <USBUART_Dp.h>
#include <USBUART_Dp_aliases.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/

