/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0 Component Pack 7
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <USBUART_1.h>
#include <USBUART_1_audio.h>
#include <USBUART_1_cdc.h>
#include <USBUART_1_hid.h>
#include <USBUART_1_midi.h>
#include <USBUART_1_pvt.h>
#include <Timer_1.h>
#include <LED.h>
#include <LED_aliases.h>
#include <timer_clock.h>
#include <V_bus.h>
#include <V_bus_aliases.h>
#include <USB_EN_ISR.h>
#include <USB_DIS_ISR.h>
#include <USBUART_1_Dm.h>
#include <USBUART_1_Dm_aliases.h>
#include <USBUART_1_Dp.h>
#include <USBUART_1_Dp_aliases.h>
#include <USBUART_1_Vbus_ps.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/

