/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0 Component Pack 7
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <RTC.h>
#include <RGB_LED.h>
#include <RGB_LED_aliases.h>
#include <Vbus.h>
#include <Vbus_aliases.h>
#include <Vbus_IRQ.h>
#include <Em_EEPROM.h>
#include <PWM0_CTRL.h>
#include <EEPROM_R.h>
#include <Sensor_In.h>
#include <Sensor_In_aliases.h>
#include <ADC.h>
#include <StartCollection_B.h>
#include <StartCollection_B_aliases.h>
#include <StopCollection_B.h>
#include <StopCollection_B_aliases.h>
#include <StopCollection_IRQ.h>
#include <StartCollection_IRQ.h>
#include <USBUART.h>
#include <USBUART_audio.h>
#include <USBUART_cdc.h>
#include <USBUART_hid.h>
#include <USBUART_midi.h>
#include <USBUART_pvt.h>
#include <PWM1_CTRL.h>
#include <LED_PWM.h>
#include <Batt_Monitor.h>
#include <Batt_Monitor_aliases.h>
#include <SOLID_LED_CTRL.h>
#include <ADC_MUX.h>
#include <ADC_AMux.h>
#include <ADC_Ext_CP_Clk.h>
#include <ADC_IRQ.h>
#include <ADC_theACLK.h>
#include <USBUART_Dm.h>
#include <USBUART_Dm_aliases.h>
#include <USBUART_Dp.h>
#include <USBUART_Dp_aliases.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/

